local global = vim.g
local o = vim.opt

o.autoindent = true
--  o.autoread = true ## Default already on
o.clipboard = "unnamedplus"
o.completeopt = "menu,preview,noinsert"
o.guicursor = "a:blinkon100"
o.icon = true
o.inccommand = "split"
o.mouse = "a"
o.ruler = true
o.hidden = true
o.showcmd = true
o.showmatch = true
o.splitright = true
o.splitbelow = true
o.number = true
o.relativenumber = true
o.tabstop = 2
o.syntax = "on"
o.termguicolors = true
o.title = true
o.ttimeoutlen = 50
 -- o.verbose = 0 # it is default, change after research
o.shiftwidth = 2
